### ISSUE TITLE
how can the pairing.a file compiled in ubuntu but work in mac?

### ISSUE THREAD

**Issue by kangkang333** [ucbrise/jedi-pairing#5]

**Comment by samkumar** [comment]
If you would like to use this library on a Mac computer, I would recommend building `pairing.a` on a Mac.

If you have more details on your use case, I can try giving more specific advice.

**Comment by kangkang333** [comment]
I am trying to make a pairing.a file on mac, but the assembly file prompts errors：

as  src/core/arch/x86_64/bigint.s -o bin/src/core/arch/x86_64/bigint.o
src/core/arch/x86_64/bigint.s:37:1: error: unknown directive
.type embedded_pairing_core_arch_x86_64_bigint_384_add, @function
^
src/core/arch/x86_64/bigint.s:62:1: error: unknown directive
.type embedded_pairing_core_arch_x86_64_bigint_384_subtract, @function
^
src/core/arch/x86_64/bigint.s:87:1: error: unknown directive
.type embedded_pairing_core_arch_x86_64_bigint_384_multiply2, @function
^
src/core/arch/x86_64/bigint.s:112:1: error: unknown directive
.type embedded_pairing_core_arch_x86_64_fpbase_384_multiply2, @function
^
src/core/arch/x86_64/bigint.s:189:1: error: unknown directive
.type embedded_pairing_core_arch_x86_64_fpbase_384_add, @function
^
src/core/arch/x86_64/bigint.s:270:1: error: unknown directive
.type embedded_pairing_core_arch_x86_64_fpbase_384_subtract, @function
^
make: *** [bin/src/core/arch/x86_64/bigint.o] Error 1

**Comment by kangkang333** [comment]
There are some differences between assembly on mac and assembly on Linux：
 1. assembly on Linux：
     .globl  my_function
    .type   my_function,@function
     my_function:
2. assembly on Mac:
    .globl  _my_function
    _my_function:

https://stackoverflow.com/questions/19720084/what-is-the-difference-between-assembly-on-mac-and-assembly-on-linux/19725269#19725269

**Comment by kangkang333** [comment]
There are some other differences: 
[missing comma](https://github.com/ucbrise/jedi-pairing/blob/c4bf151b8d2b560973cb3805f9b5f4a144597f7e/src/core/arch/x86_64/multiply.s#L177)

    # Iteration i = 4 (word 56(%rdi) in rcx, word 64(%rdi) in rbp)
    movq 32(%rsi), %r9
    muladd64 %r9, (%rsi), %r13
    muladdcarry64 %r9, 8(%rsi), %r14, %r8
    muladdcarry64 %r9, 16(%rsi), %r15, %r8
